### ISSUE TITLE
add Eigen3 & OpenCV as external project for CI

### ISSUE THREAD

**Issue by gocarlos** [OpenMapper/OpenMapper#7]
Cmake assumes that one has OpenCV and Eigen3 installed on the system. 
As travis does not have those dependencies installed, the build fails

**Comment by nidegen** [comment]
yes it is quite a mess. on macOS, the builds for g20 and DBow2 do not work either, so  i am not sure how to proceed

i thought about adding g20 and DBoW2 as submodules from their github repo, but thay are also outdated, such as that they use opencv 2.X which is outdated.

on the other hand, we can rewrite our ORB_SLAM fork so that it is more flexible?

**Comment by gocarlos** [comment]
I think this is a good idea, we can then remove or adapt the pangolin dependency...

**Comment by nidegen** [comment]
btw, why not `sudo apt-get install libopencv-dev` instead of building it for travis?:)

**Comment by gocarlos** [comment]
I wanted opencv 3.+, 
I think libopencv-dev is 2.4

**Comment by nidegen** [comment]
i see
